### ISSUE TITLE
Fail to compile in windows 7

### ISSUE THREAD

**Issue by willard-yuan** [LeszekSwirski/pupiltracker#2]
Hi Leszek, 

I try to build the **pupiltracker**, and it throw the following error:

``` sh
1>  utils.cpp
1>c:\program files (x86)\microsoft visual studio 10.0\vc\include\random(1604): error C2064: Entries are not calculated as a function of the parameter accepts 0
```

The environment is Windows 7 and VS 2010.  I think the main reason lead to this is the int `pupiltracker::random(int min, int max)` and `int pupiltracker::random(int min, int max, unsigned int seed)`. Would you tell me how to fix it?

**Comment by LeszekSwirski** [comment]
VS2010 might be a bit old, can you try with 2015? You can [download the community edition](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx) for free.

**Comment by willard-yuan** [comment]
@LeszekSwirski I change it to OS X and it runs successfully. I have read your paper **Robust real-time pupil tracking in highly off-axis images**. I can fully understand the paper, but when I test it on a video or a picture, the result seems to be not good. The followings is a result I get:
<img width="300" alt="screen shot 2015-11-15 at 16 13 48" src="https://cloud.githubusercontent.com/assets/5379711/11167987/6d900f24-8bb6-11e5-8065-edecb5a985f5.png">
then I change to a small eye image( I used a HOG with linear SVM to get the eye area), the result is as followings:
<img width="300" alt="screen shot 2015-11-15 at 16 37 36" src="https://cloud.githubusercontent.com/assets/5379711/11168002/3468f458-8bb7-11e5-8970-a31d25075dc5.png">
The fitted ellipse by RANSAC draw on the result image is smaller than the size of the gaze. I'm reading the code fully now. How do I tune the parameters to get a good result?

**Comment by LeszekSwirski** [comment]
Have you adjusted the minimum and maximum pupil radius?

**Comment by willard-yuan** [comment]
@LeszekSwirski I have adjusted the `params.Radius_Min` to 0 and `params.Radius_Max` to 50. Now it works great. Using the same image above, I get the result as follows:
<img width="300" alt="screen shot 2015-11-15 at 17 09 01" src="https://cloud.githubusercontent.com/assets/5379711/11168096/bd0b38e4-8bbb-11e5-9c58-58c1f07b1d4f.png">

I'm really interested in your research and found you have do a lot of work in gaze tracking and eye model fitting. I'm really appreciate for your help and your great works. Thanks!
